services:
  # Service 1 : IA (Python)
  ai-engine:
    build: ./ai-engine
    container_name: voice_ai_engine
    ports:
      - "8000:8000"
    volumes:
      - ./ai-engine:/app
    environment:
      - MODEL_TYPE=small
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  # Service 2 : API Gateway (Node)
  api-gateway:
    build: ./api-gateway
    container_name: voice_api_gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - ai-engine
    environment:
      - AI_SERVICE_URL=${AI_SERVICE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

  # Service 3 : Database
  db:
    image: postgres:15-alpine
    container_name: voice_db
    restart: always
    environment:
      POSTGRES_USER: voice_user
      POSTGRES_PASSWORD: voice_password
      POSTGRES_DB: voice_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optionnel, utile si tu veux inspecter la DB depuis ton PC

volumes:
  postgres_data:
